#!/usr/bin/env node

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import fetch from "node-fetch";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";

// The base URL of the Skiller backend. For local dev, this might be localhost.
// In production, it would be the real SaaS URL.
const API_BASE_URL = process.env.SKILLER_API_URL || "http://localhost:3001/api";

const server = new Server(
  {
    name: "skiller-mcp-server",
    version: "1.0.0",
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

// Define available tools
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      {
        name: "search_skills",
        description: "Search for available AI skills generated by Skiller.",
        inputSchema: {
          type: "object",
          properties: {
            query: {
              type: "string",
              description: "The search query (e.g. 'landing page', 'api integration')",
            },
          },
          required: ["query"],
        },
      },
      {
        name: "install_skill",
        description: "Install a specific skill from Skiller into the local environment.",
        inputSchema: {
          type: "object",
          properties: {
            skill_id: {
              type: "string",
              description: "The UUID of the skill to install",
            },
            target_dir: {
              type: "string",
              description: "Optional custom directory to extract the skill (defaults to ~/.agents/skills or ~/.claude/skills depending on context)",
            },
          },
          required: ["skill_id"],
        },
      }
    ],
  };
});

// Handle tool execution
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  try {
    if (name === "search_skills") {
      const query = String(args?.query || "");
      const response = await fetch(`${API_BASE_URL}/skills?q=${encodeURIComponent(query)}`);
      
      if (!response.ok) {
        throw new Error(`Failed to fetch skills: ${response.statusText}`);
      }
      
      const skills = await response.json();
      
      // Basic fallback if API doesn't filter
      const filtered = Array.isArray(skills) 
        ? skills.filter((s: any) => 
            (s.name && s.name.toLowerCase().includes(query.toLowerCase())) ||
            (s.description && s.description.toLowerCase().includes(query.toLowerCase()))
          )
        : [];
        
      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(filtered.slice(0, 5), null, 2),
          },
        ],
      };
    } 
    
    else if (name === "install_skill") {
      const skillId = String(args?.skill_id);
      let targetDir = args?.target_dir ? String(args.target_dir) : null;
      
      if (!targetDir) {
        // Default to ~/.agents/skills if not specified
        targetDir = path.join(os.homedir(), ".agents", "skills");
      }
      
      const response = await fetch(`${API_BASE_URL}/skills/${skillId}`);
      if (!response.ok) {
        throw new Error(`Failed to fetch skill details: ${response.statusText}`);
      }
      
      const skillData: any = await response.json();
      const skillPackage = skillData.skillPackage;
      
      if (!skillPackage || !skillPackage.root || !skillPackage.blobs) {
        throw new Error(`Skill ${skillId} does not have a valid skillPackage.`);
      }

      // Create base target directory
      // E.g., ~/.agents/skills/{skillName}
      // sanitize skill name for folder
      const safeSkillName = (skillData.name || skillId).replace(/[^a-z0-9_.-]/gi, '_').toLowerCase();
      const finalDir = path.join(targetDir, safeSkillName);
      
      fs.mkdirSync(finalDir, { recursive: true });

      let filesWritten = 0;

      const traverseTree = (node: any, currentPath: string) => {
        const fullPath = path.join(currentPath, node.name);
        
        if (node.type === "directory") {
          fs.mkdirSync(fullPath, { recursive: true });
          if (node.children) {
            node.children.forEach((child: any) => traverseTree(child, fullPath));
          }
        } else if (node.type === "file" && node.sha) {
          const blob = skillPackage.blobs[node.sha];
          if (blob && blob.content) {
            // ensure parent directory exists
            fs.mkdirSync(path.dirname(fullPath), { recursive: true });
            fs.writeFileSync(fullPath, blob.content, "utf-8");
            filesWritten++;
          }
        }
      };

      // Traverse children of root so we don't create a 'plugin' root folder inside the target dir
      if (skillPackage.root.children) {
        skillPackage.root.children.forEach((child: any) => traverseTree(child, finalDir));
      }

      return {
        content: [
          {
            type: "text",
            text: `Successfully installed skill '${skillData.name}' to ${finalDir}.\n${filesWritten} files written.`,
          },
        ],
      };
    }

    throw new Error(`Unknown tool: ${name}`);
  } catch (error: any) {
    return {
      isError: true,
      content: [
        {
          type: "text",
          text: `Error: ${error.message}`,
        },
      ],
    };
  }
});

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("Skiller MCP Server running on stdio");
}

main().catch((error) => {
  console.error("Fatal error running MCP server:", error);
  process.exit(1);
});
