#!/usr/bin/env node

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import fetch from "node-fetch";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";

const API_BASE_URL = process.env.SKILLER_API_URL;
if (!API_BASE_URL) {
  throw new Error("SKILLER_API_URL is required in the environment variables.");
}

// ---------------------------------------------------------------------------
// Tipos do skillPackage retornado pela API
// ---------------------------------------------------------------------------

interface BlobEntry {
  content: string;
}

interface TreeNode {
  name: string;
  type: "file" | "directory";
  sha?: string;
  children?: TreeNode[];
}

interface SkillPackage {
  root: TreeNode;
  blobs: Record<string, BlobEntry>;
}

interface SkillData {
  id: string;
  name?: string;
  description?: string;
  skillPackage?: SkillPackage;
}

interface SkillSummary {
  id: string;
  name?: string;
  description?: string;
}

// ---------------------------------------------------------------------------

const server = new Server(
  {
    name: "skiller-mcp-server",
    version: "1.0.0",
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

// Define available tools
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      {
        name: "search_skills",
        description: "Search for available AI skills generated by Skiller.",
        inputSchema: {
          type: "object",
          properties: {
            query: {
              type: "string",
              description: "The search query (e.g. 'landing page', 'api integration')",
            },
          },
          required: ["query"],
        },
      },
      {
        name: "install_skill",
        description: "Install a specific skill from Skiller into the local environment.",
        inputSchema: {
          type: "object",
          properties: {
            skill_id: {
              type: "string",
              description: "The UUID of the skill to install",
            },
            target_dir: {
              type: "string",
              description: "Optional custom directory to extract the skill (defaults to ~/.agents/skills)",
            },
          },
          required: ["skill_id"],
        },
      }
    ],
  };
});

// ---------------------------------------------------------------------------
// Proteção contra path traversal — AGENTS.md: skill é entrada não confiável.
//
// Um `node.name` vindo da API pode ser "../../../.bashrc" ou "/etc/passwd".
// Resolvemos o caminho completo e comparamos com `finalDir` antes de criar
// qualquer arquivo. Se o caminho resolvido não começar com `finalDir/`, a
// árvore inteira é abortada com erro visível no log do cliente.
// ---------------------------------------------------------------------------

function assertSafePath(resolved: string, sandbox: string): void {
  const safeBase = path.resolve(sandbox) + path.sep;
  if (!resolved.startsWith(safeBase)) {
    throw new Error(
      `Path traversal bloqueado: "${resolved}" está fora do sandbox "${sandbox}"`
    );
  }
}

function traverseTree(
  node: TreeNode,
  currentPath: string,
  sandbox: string,
  pkg: SkillPackage,
  counter: { files: number }
): void {
  // Rejeitar nomes absolutos ou que contenham separadores suspeitos antes mesmo
  // de montar o caminho — defesa em profundidade além do `assertSafePath`.
  if (
    path.isAbsolute(node.name) ||
    node.name.includes("..") ||
    node.name.includes(".git") ||
    node.name.startsWith("~")
  ) {
    throw new Error(`Nome de arquivo inválido recebido da skill: "${node.name}"`);
  }

  const fullPath = path.resolve(currentPath, node.name);
  assertSafePath(fullPath, sandbox);

  if (node.type === "directory") {
    fs.mkdirSync(fullPath, { recursive: true });
    for (const child of node.children ?? []) {
      traverseTree(child, fullPath, sandbox, pkg, counter);
    }
  } else if (node.type === "file" && node.sha) {
    const blob = pkg.blobs[node.sha];
    if (blob?.content) {
      fs.mkdirSync(path.dirname(fullPath), { recursive: true });
      fs.writeFileSync(fullPath, blob.content, "utf-8");
      counter.files++;
    }
  }
}

// Handle tool execution
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  try {
    if (name === "search_skills") {
      const query = String(args?.query ?? "");
      const response = await fetch(`${API_BASE_URL}/skills?q=${encodeURIComponent(query)}`);

      if (!response.ok) {
        throw new Error(`Failed to fetch skills: ${response.statusText}`);
      }

      const raw = await response.json();
      const skills = Array.isArray(raw) ? (raw as SkillSummary[]) : [];

      // Fallback client-side filter caso a API não filtre por query
      const filtered = skills.filter(s =>
        (s.name?.toLowerCase().includes(query.toLowerCase())) ||
        (s.description?.toLowerCase().includes(query.toLowerCase()))
      );

      return {
        content: [
          {
            type: "text" as const,
            text: JSON.stringify(filtered.slice(0, 5), null, 2),
          },
        ],
      };
    }

    if (name === "install_skill") {
      const skillId = String(args?.skill_id ?? "");
      if (!skillId) throw new Error("skill_id is required");

      const baseDir = args?.target_dir
        ? String(args.target_dir)
        : path.join(os.homedir(), ".agents", "skills");

      const response = await fetch(`${API_BASE_URL}/skills/${skillId}`);
      if (!response.ok) {
        throw new Error(`Failed to fetch skill details: ${response.statusText}`);
      }

      const skillData = await response.json() as SkillData;
      const skillPackage = skillData.skillPackage;

      if (!skillPackage?.root || !skillPackage.blobs) {
        throw new Error(`Skill ${skillId} does not have a valid skillPackage.`);
      }

      // Sanitiza o nome da skill para uso como nome de diretório
      const safeSkillName = (skillData.name ?? skillId)
        .replace(/[^a-z0-9_.-]/gi, "_")
        .toLowerCase();
      const finalDir = path.resolve(baseDir, safeSkillName);

      fs.mkdirSync(finalDir, { recursive: true });

      const counter = { files: 0 };

      // Itera os filhos do root diretamente — evita criar pasta "root" dentro de finalDir
      for (const child of skillPackage.root.children ?? []) {
        traverseTree(child, finalDir, finalDir, skillPackage, counter);
      }

      return {
        content: [
          {
            type: "text" as const,
            text: `Skill '${skillData.name ?? skillId}' instalada em ${finalDir}.\n${counter.files} arquivo(s) escritos.`,
          },
        ],
      };
    }

    throw new Error(`Unknown tool: ${name}`);
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    return {
      isError: true,
      content: [
        {
          type: "text" as const,
          text: `Error: ${message}`,
        },
      ],
    };
  }
});

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("Skiller MCP Server running on stdio");
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error("Fatal error running MCP server:", message);
  process.exit(1);
});
